"""
Core data models for Academic Radar.
Defines the structure of research profiles, papers, and queries.
"""
from datetime import datetime
from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field


class QueryType(str, Enum):
    """Types of search queries generated by The Abstractor."""
    DIRECT = "direct"  # Domain-specific keywords
    ABSTRACTED = "abstracted"  # Mathematical isomorphisms
    SOLUTION_SEEKING = "solution_seeking"  # Pain point solutions


class ResearchProfile(BaseModel):
    """The user's research DNA extracted from their papers."""
    core_task: str = Field(
        description="Primary research objective (e.g., 'Time-series forecasting')"
    )
    mathematical_framework: str = Field(
        description="Mathematical foundations (e.g., 'Non-linear dynamics, Bayesian inference')"
    )
    pain_points: List[str] = Field(
        description="Constraints and challenges (e.g., ['High inference latency', 'OOM errors'])"
    )
    domain_keywords: List[str] = Field(
        description="Domain-specific terminology (e.g., ['traffic flow', 'congestion'])"
    )
    methodologies: List[str] = Field(
        description="Current methods being used (e.g., ['LSTM', 'Graph Neural Networks'])"
    )
    created_at: datetime = Field(default_factory=datetime.utcnow)
    source_papers: List[str] = Field(
        default_factory=list,
        description="Paths to PDFs used for profiling"
    )

    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class SearchQuery(BaseModel):
    """A query generated by The Abstractor."""
    query_type: QueryType
    query_string: str = Field(
        description="The actual search query text"
    )
    rationale: str = Field(
        description="Why this query helps find isomorphic contributions"
    )
    expected_domains: List[str] = Field(
        default_factory=list,
        description="Fields we expect this to surface (for validation)"
    )


class PaperMetadata(BaseModel):
    """Metadata for a discovered paper."""
    title: str
    authors: List[str]
    abstract: str
    publication_date: datetime
    doi: Optional[str] = None
    openalex_id: str
    url: Optional[str] = None
    primary_field: Optional[str] = None
    cited_by_count: int = 0
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }


class AnalyzedPaper(BaseModel):
    """A paper analyzed by The Analyst with borrowability scoring."""
    metadata: PaperMetadata
    borrowability_score: float = Field(
        ge=0.0, le=1.0,
        description="How applicable the method is (0-1)"
    )
    methodology_summary: str = Field(
        description="Key techniques extracted from the paper"
    )
    isomorphic_connection: str = Field(
        description="'Even though this paper is about X, it uses Y which addresses your Z'"
    )
    practical_application: str = Field(
        description="How to adapt this method to the user's work"
    )
    confidence: str = Field(
        description="High/Medium/Low confidence in the analysis"
    )
    source_query_type: QueryType = Field(
        description="Which query type surfaced this paper"
    )


class EmailReport(BaseModel):
    """Structured email content."""
    subject: str
    html_body: str
    plain_text_body: str
    papers_count: int
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        json_encoders = {
            datetime: lambda v: v.isoformat()
        }
